groups:
  - name: backup_alerts
    interval: 5m
    rules:
      - alert: BackupDiskSpaceLow
        expr: |
          (
            (node_filesystem_avail_bytes{mountpoint="/opt"} / node_filesystem_size_bytes{mountpoint="/opt"}) * 100
          ) < 20
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Мало места на диске для бэкапов"

      - alert: BackupDiskSpaceCritical
        expr: |
          (
            (node_filesystem_avail_bytes{mountpoint="/opt"} / node_filesystem_size_bytes{mountpoint="/opt"}) * 100
          ) < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Критически мало места"

      - alert: BackupInodeUsageHigh
        expr: |
          (
            (node_filesystem_files_free{mountpoint="/opt"} / node_filesystem_files{mountpoint="/opt"}) * 100
          ) < 20
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Много inode занято"
